#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

int main()
{
	int num; // holding a random number generated by computer
	int guess; // holds the guess of the user
	bool isGuessed; // true if user guessed the number correctly
	int numTries = 0;
	int diff;

	srand(time(0)); // initialize randomness with time
	num = rand() % 100; // ensure the number is 0 to 100

	isGuessed = false;

	cout << "I have a number between 0 and 100. Try to guess what it is." << endl << endl;

	while (!isGuessed)
	{
		cout << "So, what is your guess? ";
		cin >> guess;
		diff = guess - num;
		numTries++;

		if (numTries > 6)
		{
			cout << "try again" << endl;
			break;
		}
		else
		{

			if (diff == 0)
			{
				cout << "Phew... You got it!!" << endl << endl;
				isGuessed = true;
			}
			else if (diff < -50)
			{
				cout << "way too low!" << endl;
			}
			else if (diff > -15)
			{
				cout << "Your guess is too low, go higher!" << endl;
			}
			else if (diff < 0)
			{
				cout << "low, but getting closer" << endl;
			}
			else if (diff >50)
			{
				cout << "Way too high!" << endl;
			}
			else if (diff > 15)
			{
				cout << "Your guess is too high, go lower!" << endl;
			}
			else if (diff > 0)
			{
				cout << "high, but getting closer" << endl;
			}
		}
	}

	system("PAUSE");
	return 0;
}
